apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ include "bookyp.fullname" . }}-backend-config"
  labels:
    {{- include "bookyp.labels" . | nindent 4 }}
data:
  BACKEND_HOST: {{ include "bookyp.backendURL" . }}
  BACKEND_SECRET: {{ .Values.backend.jwtSecret | quote }}
  BACKEND_OAUTH_REDIRECT_URL: "https://{{ include "bookyp.frontendURL" . }}/"
  BACKEND_KEYCLOAK_SUBDOMAIN: {{ .Values.keycloak.subdomain | quote }}
  BACKEND_KEYCLOAK_CLIENT: {{ .Values.keycloak.client | quote }}
  BACKEND_KEYCLOAK_SECRET: {{ .Values.keycloak.secret | quote }}
  BACKEND_DB_URI: {{ include "bookyp.backendDatabaseURI" . | quote }}
