apiVersion: v1
kind: Secret
metadata:
  name: "{{ include "bookyp.fullname" . }}-backend-secret"
  labels:
    {{- include "bookyp.labels" . | nindent 4 }}
type: Opaque
stringData:
  BACKEND_SECRET: {{ .Values.backend.jwtSecret | quote }}
  BACKEND_KEYCLOAK_SECRET: {{ .Values.backend.keycloak.secret | quote }}
  BACKEND_DB_URI: {{ include "bookyp.backendDatabaseURI" . | quote }}
  BACKEND_MAIL_PASSWORD: {{ .Values.backend.mail.password | quote }}
  BACKEND_S3_SECRET_KEY: {{ .Values.backend.s3.secretKey | quote }}
  BACKEND_PAYMENT_TOKEN: {{ .Values.backend.payment.token }}
