apiVersion: v1
kind: Service
metadata:
  name: "{{ include "bookyp.fullname" . }}-backend"
  labels:
    {{- include "bookyp.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 4000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "bookyp.selectorLabelsBackend" . | nindent 4 }}
