stages:
  - prepare
  - build
  - build-docker
  - test
  - deploy-prepare
  - deploy
  - deploy-test
  - storybook
  - storybook-deploy
  - cleanup

variables:
  GIT_DEPTH: 10
  REGISTRY: registry.geprog.com
  REGISTRY_NAMESPACE: bookyp
  BASE_DOMAIN: 'bookyp.de'

.main-pipeline-files: &main_pipeline_files
  - .ci/**/*
  - packages/**/*
  - .commitlintrc.js
  - .gitlab-ci.yml
  - .huskyrc.js
  - .lintstagedrc.js
  - .prettierignore
  - .prettierrc.js
  - package.json
  - tsconfig.json
  - pnpm-lock.yaml
  - pnpm-workspace.yaml

.node-template:
  image: registry.geprog.com/docker.io/library/node:14.16.0-buster
  before_script:
    - curl -f https://get.pnpm.io/v6.js | node - add --global pnpm@6
    - pnpm config set store-dir .pnpm-store
    - time pnpm install
  cache:
    key: bookyp # re-use cache for all jobs
    paths:
      # - node_modules
      # - packages/*/node_modules
      - .pnpm-store
    policy: pull # cache should normally only be read to save time

.helm-template:
  image:
    name: registry.geprog.com/docker.io/alpine/helm:3.5.3
    entrypoint: ['']
  dependencies: [] # don't load any artifacts

.kubectl-template:
  image:
    name: registry.geprog.com/docker.io/bitnami/kubectl:1.20.5
    entrypoint: ['']
  dependencies: [] # don't load any artifacts

.kaniko-template:
  image:
    name: gcr.io/kaniko-project/executor:v1.6.0-debug
    entrypoint: ['']

.minio-template:
  image:
    name: registry.geprog.com/docker.io/minio/mc:RELEASE.2021-03-23T05-46-11Z
    entrypoint: ['']

################# PREPARE #################

install-dependencies:
  extends: .node-template
  stage: prepare
  before_script:
    - curl -f https://get.pnpm.io/v6.js | node - add --global pnpm@6
    - pnpm config set store-dir .pnpm-store
  script:
    - time pnpm install # install dependencies
    - du -sh .pnpm-store
  cache:
    policy: pull-push # fetch data from previous installs and update them
  # artifacts:
  #   paths:
  #     - packages/*/dist
  #   expire_in: 1 day
  rules:
    - if: '$CI_MERGE_REQUEST_ID' # if pipeline runs on merge request
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
  interruptible: true

################# BUILD #################

build-frontend:
  extends: .node-template
  stage: build
  needs:
    - install-dependencies
  script:
    - pnpm --filter @bookyp/frontend... build
  artifacts:
    paths:
      - packages/frontend/dist
    expire_in: 1 day
  rules:
    - if: '$CI_MERGE_REQUEST_ID' # if pipeline runs on merge request
      changes: *main_pipeline_files
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
  interruptible: true

build-backend:
  extends: .node-template
  stage: build
  needs:
    - install-dependencies
  script:
    - pnpm --filter @bookyp/backend... build
  artifacts:
    paths:
      - packages/backend/dist
    expire_in: 1 day
  rules:
    - if: '$CI_MERGE_REQUEST_ID' # if pipeline runs on merge request
      changes: *main_pipeline_files
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
  interruptible: true

build-core:
  extends: .node-template
  stage: build
  script:
    - pnpm --filter @bookyp/core... build
  artifacts:
    paths:
      - packages/core/dist
    expire_in: 1 day
  rules:
    - if: '$CI_MERGE_REQUEST_ID' # if pipeline runs on merge request
      changes: *main_pipeline_files
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
  interruptible: true

################# BUILD DOCKER #################

build-docker-frontend:
  extends:
    - .kaniko-template
  stage: build-docker
  needs:
    - build-frontend
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$REGISTRY\":{\"username\":\"$REGISTRY_USER\",\"password\":\"$REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/.ci/frontend.Dockerfile --destination "$REGISTRY"/"$REGISTRY_NAMESPACE"/frontend:${CI_COMMIT_REF_SLUG}-${CI_COMMIT_SHA}
  rules:
    - if: '$CI_MERGE_REQUEST_ID' # if pipeline runs on merge request
      changes: *main_pipeline_files
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
  interruptible: true

build-docker-backend:
  extends:
    - .kaniko-template
  stage: build-docker
  needs:
    - build-backend
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$REGISTRY\":{\"username\":\"$REGISTRY_USER\",\"password\":\"$REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/.ci/backend.Dockerfile --destination "$REGISTRY"/"$REGISTRY_NAMESPACE"/backend:${CI_COMMIT_REF_SLUG}-${CI_COMMIT_SHA}
  rules:
    - if: '$CI_MERGE_REQUEST_ID' # if pipeline runs on merge request
      changes: *main_pipeline_files
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
  interruptible: true

################# TEST #################

### Type check
.typecheck-template:
  extends: .node-template
  stage: test
  needs:
    - build-core
    - install-dependencies
  variables:
    NODE_ENV: 'test'
  rules:
    - if: '$CI_MERGE_REQUEST_ID' # if pipeline runs on merge request
      changes: *main_pipeline_files
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
  interruptible: true

typecheck-backend:
  extends: .typecheck-template
  script:
    - pnpm run --filter @bookyp/backend typecheck

typecheck-frontend:
  extends: .typecheck-template
  script:
    - pnpm run --filter @bookyp/frontend typecheck

typecheck-core:
  extends: .typecheck-template
  script:
    - pnpm run --filter @bookyp/core typecheck

### Lint
.lint-template:
  extends: .node-template
  stage: test
  needs:
    - build-core
    - install-dependencies
  variables:
    NODE_ENV: 'test'
  rules:
    - if: '$CI_MERGE_REQUEST_ID' # if pipeline runs on merge request
      changes: *main_pipeline_files
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
  interruptible: true

lint-formatting:
  extends: .lint-template
  script:
    - pnpm run lint:formatting

lint-backend:
  extends: .lint-template
  script:
    - pnpm run --filter @bookyp/backend lint

lint-frontend:
  extends: .lint-template
  script:
    - pnpm run --filter @bookyp/frontend lint

lint-core:
  extends: .lint-template
  script:
    - pnpm run --filter @bookyp/core lint

### Unit test
.unit-test-template:
  extends: .node-template
  stage: test
  needs:
    - build-core
    - install-dependencies
  coverage: '/All\sfiles.*?\s+(\d+.\d+)/'
  variables:
    NODE_ENV: 'test'
  rules:
    - if: '$CI_MERGE_REQUEST_ID' # if pipeline runs on merge request
      changes: *main_pipeline_files
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
  interruptible: true

unit-test-backend:
  extends: .unit-test-template
  artifacts:
    when: always
    paths:
      - packages/backend/coverage
    expire_in: 1 day
    reports:
      cobertura: packages/backend/coverage/cobertura-coverage.xml
      junit:
        - packages/backend/junit.xml
  script:
    - pnpm run --filter @bookyp/backend test

unit-test-frontend:
  extends: .unit-test-template
  artifacts:
    when: always
    paths:
      - packages/frontend/coverage
    expire_in: 1 day
    reports:
      cobertura: packages/frontend/coverage/cobertura-coverage.xml
      junit:
        - packages/frontend/junit.xml
  script:
    - pnpm run --filter @bookyp/frontend test

unit-test-core:
  extends: .unit-test-template
  artifacts:
    when: always
    paths:
      - packages/core/coverage
    expire_in: 1 day
    reports:
      cobertura: packages/core/coverage/cobertura-coverage.xml
      junit:
        - packages/core/junit.xml
  script:
    - pnpm run --filter @bookyp/core test

### Misc
renovate-config-validator:
  stage: test
  needs: []
  image: registry.geprog.com/docker.io/renovate/renovate:25.28.1
  script:
    - renovate-config-validator
  rules:
    - if: '$CI_MERGE_REQUEST_ID' # if pipeline runs on merge request
      changes:
        - .gitlab-ci.yml
        - renovate.json
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
  interruptible: true

spell-check:
  extends: .node-template
  stage: test
  needs:
    - install-dependencies
  script:
    - pnpm run spellcheck
  rules:
    - if: '$CI_MERGE_REQUEST_ID' # if pipeline runs on merge request
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
  interruptible: true

helm-lint:
  extends:
    - .helm-template
  stage: test
  needs: []
  script:
    - helm lint .ci/charts/bookyp
    - helm lint .ci/charts/storybook
  rules:
    - if: '$CI_MERGE_REQUEST_ID' # if pipeline runs on merge request
      changes:
        - .ci/charts/**/*
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
  interruptible: true

################# DEPLOY #################

.review-environment:
  environment:
    name: app/$CI_COMMIT_REF_SLUG
    url: https://${CI_ENVIRONMENT_SLUG}.app.${BASE_DOMAIN}/
    deployment_tier: development
    on_stop: review-stop
    auto_stop_in: 3 days # stop after 3 days without new commits
    kubernetes:
      namespace: bookyp-review
  rules:
    # if pipeline runs on merge request and is triggered by renovate
    - if: '$CI_MERGE_REQUEST_ID && $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME =~ /^renovate/'
      changes: *main_pipeline_files
      when: manual
      allow_failure: true
    # if pipeline runs on merge request
    - if: '$CI_MERGE_REQUEST_ID && $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME !~ /^renovate/'
      changes: *main_pipeline_files

review-prepare:
  extends:
    - .kubectl-template
    - .review-environment
  stage: deploy-prepare
  needs: []
  script:
    - kubectl create namespace $KUBE_NAMESPACE || true
    - >
      kubectl -n $KUBE_NAMESPACE create secret docker-registry bookyp-registry-secret
      --docker-server=$REGISTRY
      --docker-username=$REGISTRY_USER
      --docker-password=$REGISTRY_PASSWORD
      --save-config --dry-run=client
      -o yaml | kubectl apply -f -
    - kubectl -n $KUBE_NAMESPACE apply -f .ci/kube/review-certificate.yml

review-deployment:
  extends:
    - .helm-template
    - .review-environment
  stage: deploy
  needs:
    - build-docker-frontend
    - build-docker-backend
    - review-prepare
  script:
    - >
      helm upgrade --namespace $KUBE_NAMESPACE --create-namespace --install
      --set environment.type=review
      --set environment.name=$CI_ENVIRONMENT_SLUG
      --set environment.url=$CI_ENVIRONMENT_URL
      --set frontend.ingress.tls.secretName=bookyp-review-frontend-tls
      --set frontend.image.tag=${CI_COMMIT_REF_SLUG}-${CI_COMMIT_SHA}
      --set backend.ingress.tls.secretName=bookyp-review-backend-tls
      --set backend.image.tag=${CI_COMMIT_REF_SLUG}-${CI_COMMIT_SHA}
      --set backend.database.password=$DEPLOY_DATABASE_PASSWORD
      --set backend.keycloak.secret=$KEYCLOAK_SECRET
      --set backend.jwtSecret=$BACKEND_JWT_SECRET
      --set gitlab.app=$CI_PROJECT_PATH_SLUG
      --set gitlab.env=$CI_ENVIRONMENT_SLUG
      bookyp-${CI_ENVIRONMENT_SLUG} .ci/charts/bookyp

review-deployment-test:
  extends:
    - .helm-template
    - .review-environment
  stage: deploy-test
  needs:
    - review-deployment
  script:
    - helm test --namespace $KUBE_NAMESPACE bookyp-${CI_ENVIRONMENT_SLUG}

review-stop:
  extends:
    - .helm-template
    - .review-environment
  stage: cleanup
  environment:
    action: stop
  variables:
    GIT_STRATEGY: none # Source: https://docs.gitlab.com/ee/ci/yaml/#environmentaction
  script:
    - helm uninstall --namespace $KUBE_NAMESPACE bookyp-${CI_ENVIRONMENT_SLUG}
  rules:
    - if: '$CI_MERGE_REQUEST_ID' # if pipeline runs on merge request
      changes: *main_pipeline_files
      when: manual
      allow_failure: true

### Production deployment

.production-environment:
  environment:
    name: app/production
    url: https://app.${BASE_DOMAIN}/
    deployment_tier: production
    kubernetes:
      namespace: bookyp-production
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'

production-prepare:
  extends:
    - .kubectl-template
    - .production-environment
  stage: deploy-prepare
  needs:
    # require tests to pass before starting production deployment
    - unit-test-backend
    - unit-test-frontend
    - unit-test-core
    - typecheck-backend
    - typecheck-frontend
    - typecheck-core
    - lint-formatting
    - lint-backend
    - lint-frontend
    - lint-core
    - helm-lint
    - spell-check
  script:
    - kubectl create namespace $KUBE_NAMESPACE || true
    - >
      kubectl -n $KUBE_NAMESPACE create secret docker-registry bookyp-registry-secret
      --docker-server=$REGISTRY
      --docker-username=$REGISTRY_USER
      --docker-password=$REGISTRY_PASSWORD
      --save-config --dry-run=client
      -o yaml | kubectl apply -f -
    - kubectl -n $KUBE_NAMESPACE apply -f .ci/kube/production-certificate.yml

production-deployment:
  extends:
    - .helm-template
    - .production-environment
  stage: deploy
  needs:
    - build-docker-frontend
    - build-docker-backend
    - production-prepare
  script:
    - >
      helm upgrade --namespace $KUBE_NAMESPACE --create-namespace --install
      --set environment.type=production
      --set environment.name=$CI_ENVIRONMENT_SLUG
      --set environment.url=$CI_ENVIRONMENT_URL
      --set frontend.ingress.tls.secretName=bookyp-production-tls
      --set backend.ingress.tls.secretName=bookyp-production-tls
      --set frontend.image.tag=${CI_COMMIT_REF_SLUG}-${CI_COMMIT_SHA}
      --set backend.image.tag=${CI_COMMIT_REF_SLUG}-${CI_COMMIT_SHA}
      --set backend.database.password=$DEPLOY_DATABASE_PASSWORD
      --set backend.keycloak.secret=$KEYCLOAK_SECRET
      --set backend.jwtSecret=$BACKEND_JWT_SECRET
      --set gitlab.app=$CI_PROJECT_PATH_SLUG
      --set gitlab.env=$CI_ENVIRONMENT_SLUG
      bookyp-${CI_ENVIRONMENT_SLUG} .ci/charts/bookyp

production-rollback:
  extends:
    - .helm-template
    - .production-environment
  stage: cleanup
  needs:
    - production-deployment
  script:
    - helm rollback --namespace $KUBE_NAMESPACE bookyp-production 0 # SOURCE: https://github.com/helm/helm/issues/1796
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
      when: manual
      allow_failure: true

################# STORYBOOK #################

.storybook-review-environment:
  environment:
    name: storybook/$CI_COMMIT_REF_SLUG
    url: https://${CI_ENVIRONMENT_SLUG}.storybook.${BASE_DOMAIN}/
    deployment_tier: development
    on_stop: storybook-stop
    auto_stop_in: 3 days # stop after 3 days without new commits
    kubernetes:
      namespace: bookyp-review
  rules:
    # if pipeline runs on merge request and is triggered by renovate
    - if: '$CI_MERGE_REQUEST_ID && $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME =~ /^renovate/'
      changes: *main_pipeline_files
      when: manual
      allow_failure: true
    # if pipeline runs on merge request
    - if: '$CI_MERGE_REQUEST_ID && $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME !~ /^renovate/'
      changes: *main_pipeline_files

storybook-build:
  extends:
    - .node-template
    - .storybook-review-environment
  stage: storybook
  needs:
    - build-core
  script:
    - pnpm --filter @bookyp/storybook build
  environment:
    action: prepare
  artifacts:
    paths:
      - packages/storybook/storybook-static
    expire_in: 1 day
  rules:
    # if pipeline on default branch
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
    # if pipeline runs on merge request and is triggered by renovate
    - if: '$CI_MERGE_REQUEST_ID && $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME =~ /^renovate/'
      changes: *main_pipeline_files
      when: manual
      allow_failure: true
    # if pipeline runs on merge request
    - if: '$CI_MERGE_REQUEST_ID && $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME !~ /^renovate/'
      changes: *main_pipeline_files
  interruptible: true

storybook-review-upload:
  extends:
    - .minio-template
    - .storybook-review-environment
  stage: storybook-deploy
  needs:
    - storybook-build
  environment:
    action: prepare
  before_script:
    - mc alias set geprog https://s3.geprog.com $S3_ACCESS_KEY $S3_SECRET_KEY
  script:
    - mc mirror --remove --overwrite ./packages/storybook/storybook-static geprog/bookyp-storybook/$CI_ENVIRONMENT_SLUG

storybook-review-deploy:
  extends:
    - .helm-template
    - .storybook-review-environment
  stage: storybook-deploy
  needs:
    - review-prepare
  script:
    - >
      helm upgrade --namespace $KUBE_NAMESPACE --create-namespace --install
      --set environment.type=review
      --set environment.name=$CI_ENVIRONMENT_SLUG
      --set environment.url=${CI_ENVIRONMENT_SLUG}.storybook.${BASE_DOMAIN}
      --set ingress.tls.secretName=bookyp-storybook-review-tls
      --set s3.accessKey=$S3_ACCESS_KEY
      --set s3.secretKey=$S3_SECRET_KEY
      --set s3.root=$CI_ENVIRONMENT_SLUG
      --set gitlab.app=$CI_PROJECT_PATH_SLUG
      --set gitlab.env=$CI_ENVIRONMENT_SLUG
      bookyp-${CI_ENVIRONMENT_SLUG} .ci/charts/storybook

storybook-stop:
  extends:
    - .helm-template
    - .storybook-review-environment
  stage: cleanup
  environment:
    action: stop
  variables:
    GIT_STRATEGY: none # Source: https://docs.gitlab.com/ee/ci/yaml/#environmentaction
  script:
    - helm uninstall --namespace $KUBE_NAMESPACE bookyp-${CI_ENVIRONMENT_SLUG}
  rules:
    - if: '$CI_MERGE_REQUEST_ID' # if pipeline runs on merge request
      changes: *main_pipeline_files
      when: manual
      allow_failure: true

.storybook-production-environment:
  environment:
    name: storybook/production
    url: https://storybook.${BASE_DOMAIN}/
    deployment_tier: production
    kubernetes:
      namespace: bookyp-production
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'

storybook-production-upload:
  extends:
    - .minio-template
    - .storybook-production-environment
  stage: storybook-deploy
  needs:
    - storybook-build
  environment:
    action: prepare
  before_script:
    - mc alias set geprog https://s3.geprog.com $S3_ACCESS_KEY $S3_SECRET_KEY
  script:
    - mc mirror --remove --overwrite ./packages/storybook/storybook-static geprog/bookyp-storybook/$CI_ENVIRONMENT_SLUG

storybook-deploy-production:
  extends:
    - .helm-template
    - .storybook-production-environment
  stage: storybook-deploy
  needs:
    - production-prepare
  script:
    - >
      helm upgrade --namespace $KUBE_NAMESPACE --create-namespace --install
      --set environment.type=production
      --set environment.name=$CI_ENVIRONMENT_SLUG
      --set environment.url=storybook.${BASE_DOMAIN}
      --set ingress.tls.secretName=bookyp-storybook-production-tls
      --set s3.accessKey=$S3_ACCESS_KEY
      --set s3.secretKey=$S3_SECRET_KEY
      --set s3.root=$CI_ENVIRONMENT_SLUG
      --set gitlab.app=$CI_PROJECT_PATH_SLUG
      --set gitlab.env=$CI_ENVIRONMENT_SLUG
      bookyp-${CI_ENVIRONMENT_SLUG} .ci/charts/storybook

################# DUMMY JOB #################

dummy:
  stage: build
  image: registry.geprog.com/docker.io/library/docker:latest
  script:
    - echo "I'm creating a successful pipeline for changes in files that otherwise don't create a pipeline."
  rules:
    - if: '$CI_MERGE_REQUEST_ID' # if pipeline runs on merge request
      changes: # ideally each of these files would have a job i.e. a linter doing something useful
        - README.md
        - docs/**/*
        - .gitlab/**/*
        - .devcontainer/**/*
        - .vscode/**/*
        - .editorconfig
        - .gitignore
        - .eslintignore
  interruptible: true
