stages:
  - prepare
  - build
  - build-docker
  - test
  - coverage
  - deploy-prepare
  - deploy
  - deploy-test
  - cleanup

variables:
  GIT_DEPTH: 10
  REGISTRY: registry.geprog.com
  REGISTRY_NAMESPACE: bookyp
  BASE_DOMAIN: 'bookyp.de'

.main-pipeline-files: &main_pipeline_files
  - .ci/**/*
  - packages/**/*
  - .commitlintrc.js
  - .gitlab-ci.yml
  - .huskyrc.js
  - .lintstagedrc.js
  - .prettierignore
  - .prettierrc.js
  - package.json
  - tsconfig.json
  - pnpm-lock.yaml
  - pnpm-workspace.yaml

.node-template:
  image: registry.geprog.com/docker.io/library/node:14.16.0-buster
  before_script:
    - curl -f https://get.pnpm.io/v6.js | node - add --global pnpm@6
    - pnpm config set store-dir .pnpm-store
    - time pnpm install
  cache:
    key: bookyp # re-use cache for all jobs
    paths:
      # - node_modules
      # - packages/*/node_modules
      - .pnpm-store
    policy: pull # cache should normally only be read to save time

################# PREPARE #################

install-dependencies:
  extends: .node-template
  stage: prepare
  before_script:
    - curl -f https://get.pnpm.io/v6.js | node - add --global pnpm@6
    - pnpm config set store-dir .pnpm-store
  script:
    - time pnpm install # install dependencies
    - du -sh .pnpm-store
  cache:
    policy: pull-push # fetch data from previous installs and update them
  # artifacts:
  #   paths:
  #     - packages/*/dist
  #   expire_in: 1 day
  rules:
    - if: '$CI_MERGE_REQUEST_ID' # check if pipeline runs on merge request
    - if: '$CI_COMMIT_BRANCH == "master"'
  interruptible: true

################# BUILD #################

build-frontend:
  extends: .node-template
  stage: build
  needs:
    - install-dependencies
  script:
    - pnpm --filter @bookyp/frontend... build
  artifacts:
    paths:
      - packages/frontend/dist
    expire_in: 1 day
  rules:
    - if: '$CI_MERGE_REQUEST_ID' # check if pipeline runs on merge request
      changes: *main_pipeline_files
    - if: '$CI_COMMIT_BRANCH == "master"'
  interruptible: true

build-backend:
  extends: .node-template
  stage: build
  needs:
    - install-dependencies
  script:
    - pnpm --filter @bookyp/backend... build
  artifacts:
    paths:
      - packages/backend/dist
    expire_in: 1 day
  rules:
    - if: '$CI_MERGE_REQUEST_ID' # check if pipeline runs on merge request
      changes: *main_pipeline_files
    - if: '$CI_COMMIT_BRANCH == "master"'
  interruptible: true

build-core:
  extends: .node-template
  stage: build
  script:
    - pnpm --filter @bookyp/core... build
  artifacts:
    paths:
      - packages/core/dist
    expire_in: 1 day
  rules:
    - if: '$CI_MERGE_REQUEST_ID' # check if pipeline runs on merge request
      changes: *main_pipeline_files
    - if: '$CI_COMMIT_BRANCH == "master"'
  interruptible: true

################# BUILD DOCKER #################

build-docker-frontend:
  image:
    name: gcr.io/kaniko-project/executor:v1.6.0-debug
    entrypoint: ['']
  stage: build-docker
  needs:
    - build-frontend
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$REGISTRY\":{\"username\":\"$REGISTRY_USER\",\"password\":\"$REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/.ci/frontend.Dockerfile --destination "$REGISTRY"/"$REGISTRY_NAMESPACE"/frontend:${CI_COMMIT_REF_SLUG}-${CI_COMMIT_SHA}
  rules:
    - if: '$CI_MERGE_REQUEST_ID' # check if pipeline runs on merge request
      changes: *main_pipeline_files
    - if: '$CI_COMMIT_BRANCH == "master"'
  interruptible: true

build-docker-backend:
  image:
    name: gcr.io/kaniko-project/executor:v1.6.0-debug
    entrypoint: ['']
  stage: build-docker
  needs:
    - build-backend
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$REGISTRY\":{\"username\":\"$REGISTRY_USER\",\"password\":\"$REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/.ci/backend.Dockerfile --destination "$REGISTRY"/"$REGISTRY_NAMESPACE"/backend:${CI_COMMIT_REF_SLUG}-${CI_COMMIT_SHA}
  rules:
    - if: '$CI_MERGE_REQUEST_ID' # check if pipeline runs on merge request
      changes: *main_pipeline_files
    - if: '$CI_COMMIT_BRANCH == "master"'
  interruptible: true

################# TEST #################

typechecking:
  extends: .node-template
  stage: test
  needs:
    - build-core
    - install-dependencies
  variables:
    NODE_ENV: 'test'
  script:
    - pnpm run typecheck
  rules:
    - if: '$CI_MERGE_REQUEST_ID' # check if pipeline runs on merge request
      changes: *main_pipeline_files
    - if: '$CI_COMMIT_BRANCH == "master"'
  interruptible: true

linting:
  extends: .node-template
  stage: test
  needs:
    - build-core
    - install-dependencies
  variables:
    NODE_ENV: 'test'
  script:
    - pnpm run lint
  rules:
    - if: '$CI_MERGE_REQUEST_ID' # check if pipeline runs on merge request
      changes: *main_pipeline_files
    - if: '$CI_COMMIT_BRANCH == "master"'
  interruptible: true

unit-tests:
  extends: .node-template
  stage: test
  needs:
    - build-core
    - install-dependencies
  artifacts:
    paths:
      - packages/*/coverage
    expire_in: 1 day
  variables:
    NODE_ENV: 'test'
  script:
    - pnpm run test
  rules:
    - if: '$CI_MERGE_REQUEST_ID' # check if pipeline runs on merge request
      changes: *main_pipeline_files
    - if: '$CI_COMMIT_BRANCH == "master"'
  interruptible: true

renovate-config-validator:
  stage: test
  needs: []
  image: registry.geprog.com/docker.io/renovate/renovate:24.74.0
  script:
    - renovate-config-validator
  rules:
    - if: '$CI_MERGE_REQUEST_ID' # check if pipeline runs on merge request
      changes:
        - .gitlab-ci.yml
        - renovate.json
    - if: '$CI_COMMIT_BRANCH == "master"'
  interruptible: true

lint-merge-request-title:
  extends: .node-template
  stage: test
  needs: []
  script:
    - echo ${CI_MERGE_REQUEST_TITLE} | ./node_modules/.bin/commitlint
  rules:
    - if: '$CI_MERGE_REQUEST_ID' # check if pipeline runs on merge request
  interruptible: true

spell-check:
  extends: .node-template
  stage: test
  needs:
    - install-dependencies
  script:
    - pnpm run spellcheck
  rules:
    - if: '$CI_MERGE_REQUEST_ID' # check if pipeline runs on merge request
    - if: '$CI_COMMIT_BRANCH == "master"'
  interruptible: true

helm-lint:
  stage: test
  needs: []
  image:
    name: registry.geprog.com/docker.io/alpine/helm:3.5.3
    entrypoint: ['']
  script:
    - helm lint .ci/charts/bookyp
  rules:
    - if: '$CI_MERGE_REQUEST_ID' # check if pipeline runs on merge request
      changes:
        - .ci/charts/bookyp/**/*
    - if: '$CI_COMMIT_BRANCH == "master"'
  interruptible: true

################# COVERAGE #################

code-coverage:
  extends: .node-template
  stage: coverage
  needs:
    - unit-tests
  variables:
    NODE_ENV: 'test'
  script:
    - pnpm run --filter @bookyp/test-coverage coverage
  coverage: '/All\sfiles.*?\s+(\d+.\d+)/'
  rules:
    - if: '$CI_MERGE_REQUEST_ID' # check if pipeline runs on merge request
      changes: *main_pipeline_files
    - if: '$CI_COMMIT_BRANCH == "master"'
  interruptible: true

################# DEPLOY #################

.deploy-base:
  image:
    name: registry.geprog.com/docker.io/alpine/helm:3.5.3
    entrypoint: ['']
  dependencies: [] # don't load any artifacts

.review-environment:
  environment:
    name: review/$CI_COMMIT_REF_SLUG
    url: https://${CI_ENVIRONMENT_SLUG}.app.${BASE_DOMAIN}/
    on_stop: review-stop
    auto_stop_in: 3 days # stop after 3 days without new commits
    kubernetes:
      namespace: bookyp-review
  rules:
    # check if pipeline runs on merge request and is triggered by renovate
    - if: '$CI_MERGE_REQUEST_ID && $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME =~ /^renovate/'
      changes: *main_pipeline_files
      when: manual
      allow_failure: true
    # check if pipeline runs on merge request
    - if: '$CI_MERGE_REQUEST_ID && $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME !~ /^renovate/'
      changes: *main_pipeline_files

review-prepare:
  extends: .review-environment
  stage: deploy-prepare
  needs: []
  image:
    name: registry.geprog.com/docker.io/bitnami/kubectl:1.20.5
    entrypoint: ['']
  script:
    - kubectl create namespace $KUBE_NAMESPACE || true
    - >
      kubectl -n $KUBE_NAMESPACE create secret docker-registry bookyp-registry-secret
      --docker-server=$REGISTRY
      --docker-username=$REGISTRY_USER
      --docker-password=$REGISTRY_PASSWORD
      --save-config --dry-run=client
      -o yaml | kubectl apply -f -
    - kubectl -n $KUBE_NAMESPACE apply -f .ci/kube/review-certificate.yml

review-deployment:
  extends:
    - .deploy-base
    - .review-environment
  stage: deploy
  needs:
    - build-docker-frontend
    - build-docker-backend
    - review-prepare
  script:
    - >
      helm upgrade --namespace $KUBE_NAMESPACE --create-namespace --install
      --values .ci/charts/bookyp/review-helm-values.yaml
      --set environment.name=$CI_ENVIRONMENT_SLUG
      --set frontend.image.tag=${CI_COMMIT_REF_SLUG}-${CI_COMMIT_SHA}
      --set backend.image.tag=${CI_COMMIT_REF_SLUG}-${CI_COMMIT_SHA}
      --set backend.database.password=$DEPLOY_DATABASE_PASSWORD
      --set backend.keycloak.secret=$KEYCLOAK_SECRET
      --set backend.jwtSecret=$BACKEND_JWT_SECRET
      --set gitlab.app=$CI_PROJECT_PATH_SLUG
      --set gitlab.env=$CI_ENVIRONMENT_SLUG
      bookyp-${CI_ENVIRONMENT_SLUG} .ci/charts/bookyp

review-deployment-test:
  extends:
    - .deploy-base
    - .review-environment
  stage: deploy-test
  needs:
    - review-deployment
  script:
    - helm test --namespace $KUBE_NAMESPACE bookyp-${CI_ENVIRONMENT_SLUG} --logs

review-stop:
  extends:
    - .deploy-base
    - .review-environment
  stage: cleanup
  environment:
    name: review/$CI_COMMIT_REF_SLUG
    action: stop
    kubernetes:
      namespace: bookyp-review
  variables:
    GIT_STRATEGY: none # Source: https://docs.gitlab.com/ee/ci/yaml/#environmentaction
  script:
    - helm uninstall --namespace $KUBE_NAMESPACE bookyp-${CI_ENVIRONMENT_SLUG}
  rules:
    - if: '$CI_MERGE_REQUEST_ID' # check if pipeline runs on merge request
      changes: *main_pipeline_files
      when: manual
      allow_failure: true

### Production deployment

.production-environment:
  environment:
    name: production
    url: https://app.${BASE_DOMAIN}/
    kubernetes:
      namespace: bookyp-production
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'

production-prepare:
  extends:
    - .production-environment
  stage: deploy-prepare
  needs:
    # require tests to pass before starting production deployment
    - unit-tests
    - typechecking
    - linting
    - helm-lint
    - spell-check
  image:
    name: registry.geprog.com/docker.io/bitnami/kubectl:1.20.5
    entrypoint: ['']
  script:
    - kubectl create namespace $KUBE_NAMESPACE || true
    - >
      kubectl -n $KUBE_NAMESPACE create secret docker-registry bookyp-registry-secret
      --docker-server=$REGISTRY
      --docker-username=$REGISTRY_USER
      --docker-password=$REGISTRY_PASSWORD
      --save-config --dry-run=client
      -o yaml | kubectl apply -f -
    - kubectl -n $KUBE_NAMESPACE apply -f .ci/kube/production-certificate.yml

production-deployment:
  extends:
    - .deploy-base
    - .production-environment
  stage: deploy
  needs:
    - build-docker-frontend
    - build-docker-backend
    - production-prepare
  script:
    - >
      helm upgrade --namespace $KUBE_NAMESPACE --create-namespace --install
      --values .ci/charts/bookyp/production-helm-values.yaml
      --set frontend.image.tag=${CI_COMMIT_REF_SLUG}-${CI_COMMIT_SHA}
      --set backend.image.tag=${CI_COMMIT_REF_SLUG}-${CI_COMMIT_SHA}
      --set backend.database.password=$DEPLOY_DATABASE_PASSWORD
      --set backend.keycloak.secret=$KEYCLOAK_SECRET
      --set backend.jwtSecret=$BACKEND_JWT_SECRET
      --set gitlab.app=$CI_PROJECT_PATH_SLUG
      --set gitlab.env=$CI_ENVIRONMENT_SLUG
      bookyp-production .ci/charts/bookyp

production-rollback:
  extends:
    - .deploy-base
    - .production-environment
  stage: cleanup
  needs:
    - production-deployment
  script:
    - helm rollback --namespace $KUBE_NAMESPACE bookyp-production 0 # SOURCE: https://github.com/helm/helm/issues/1796
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
      when: manual
      allow_failure: true

################# DUMMY JOB #################

dummy:
  stage: build
  image: registry.geprog.com/docker.io/library/docker:latest
  script:
    - echo "I'm creating a successful pipeline for changes in files that otherwise don't create a pipeline."
  rules:
    - if: '$CI_MERGE_REQUEST_ID' # check if pipeline runs on merge request
      changes: # ideally each of these files would have a job i.e. a linter doing something useful
        - README.md
        - docs/**/*
        - .gitlab/**/*
        - .devcontainer/**/*
        - .vscode/**/*
        - .editorconfig
        - .gitignore
        - .eslintignore
  interruptible: true
