enableTelemetry: 0

packageExtensions:
  "@feathersjs/express@*":
    dependencies:
      "@feathersjs/feathers": 5.0.0-pre.1
  "@intlify/cli@0.2.0":
    dependencies:
      source-map: "*"
  "@intlify/vite-plugin-vue-i18n@2.0.1":
    dependencies:
      debug: "*"
      vite: "2.0.0-beta.55"
  "@jest/transform@27.0.0-next.2":
    dependencies:
      jest-runner: 27.0.0-next.2
  "@vitejs/plugin-vue@*":
    dependencies:
      vite: 2.0.0-beta.55
  "@vue/test-utils@*":
    dependencies:
      "@vue/compiler-dom": ^3.0.1
  debug@*:
    dependencies:
      supports-color: "*"
  jest-circus@27.0.0-next.2:
    dependencies:
      slash: 3.0.0
  jest-snapshot@27.0.0-next.2:
    dependencies:
      "@babel/core": 7.12.10
  vue-jest@5.0.0-alpha.8:
    dependencies:
      "@vue/compiler-sfc": ^3.0.3
      source-map: ^0.6.0
  ws@*:
    dependencies:
      bufferutil: "*"
      utf-8-validate: "*"
  "vue-eslint-parser@*":
    dependencies:
      "@typescript-eslint/parser": "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"

yarnPath: .yarn/releases/yarn-2.4.1.cjs
