enableTelemetry: 0

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"

yarnPath: .yarn/releases/yarn-2.4.0.cjs

packageExtensions:
  "debug@*":
    dependencies:
      "supports-color": "*"
  "ws@*":
    dependencies:
      "utf-8-validate": "*"
      "bufferutil": "*"
  "@feathersjs/express@*":
    dependencies:
      "@feathersjs/feathers": "5.0.0-pre.1"
  "@vitejs/plugin-vue@*":
    dependencies:
      "vite": "2.0.0-beta.55"
  "@fullhuman/postcss-purgecss@*":
     dependencies:
      "postcss": "8.2.5"
  "@jest/transform@27.0.0-next.2":
    dependencies:
      "jest-runner": "27.0.0-next.2"
  "jest-circus@27.0.0-next.2":
    dependencies:
      "slash": "3.0.0"
  "jest-snapshot@27.0.0-next.2":
    dependencies:
      "@babel/core": "7.12.10"
