packages:
  # all packages in subdirs of packages/
  - 'packages/**'

minimumReleaseAge: 1440
trustPolicy: no-downgrade
trustPolicyExclude:
  - semver@5.7.2 || 6.3.1
overrides:
  grant: 5.4.12
  "@feathersjs/adapter-commons": 5.0.0-pre.17
  "@feathersjs/transport-commons>@feathersjs/commons": 5.0.0-pre.17
  feathers-hooks-common@7.0.0-pre.1>@feathersjs/commons: 5.0.0-pre.17
  feathers-mongoose>@feathersjs/commons: 5.0.0-pre.17
  "@feathersjs/errors": 5.0.0-pre.17
  "@feathersjs/feathers": 5.0.0-pre.17
  "@intlify/vite-plugin-vue-i18n@6.0.1>@intlify/bundle-utils": 7.0.0
  "@intlify/vite-plugin-vue-i18n@6.0.1>@intlify/shared": 10.0.0-rc.1
allowBuilds:
  core-js: false
  esbuild: true
  maplibre-gl: false
  nodemon: false
  sharp: false
  vue-demi: false
