apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ include "bookyp.fullname" . }}-payment"
  labels:
    {{- include "bookyp.labels" . | nindent 4 }}
  {{- if or (and .Values.gitlab.app .Values.gitlab.env) .Values.payment.deploymentAnnotations }}
  annotations:
    {{- with .Values.payment.deploymentAnnotations }}
      {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- include "bookyp.gitlabAnnotations" . | nindent 8 }}
  {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "bookyp.selectorLabelsPayment" . | nindent 6 }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      {{- if or (and .Values.gitlab.app .Values.gitlab.env) .Values.payment.podAnnotations }}
      annotations:
        {{- with .Values.payment.podAnnotations }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- include "bookyp.gitlabAnnotations" . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "bookyp.selectorLabelsPayment" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "bookyp.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.payment.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.payment.securityContext | nindent 12 }}
          image: "{{ .Values.payment.image.repository }}:{{ .Values.payment.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.payment.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 7171
              protocol: TCP
          envFrom:
            - configMapRef:
                name: "{{ include "bookyp.fullname" . }}-payment-config"
            - secretRef:
                name: "{{ include "bookyp.fullname" . }}-payment-secret"
          resources:
            {{- toYaml .Values.payment.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /app/data
              name: data-volume
        - name: gotenberg
          image: "{{ .Values.payment.gotenberg.image.repository }}:{{ .Values.payment.gotenberg.image.tag }}"
          imagePullPolicy: {{ .Values.payment.gotenberg.image.pullPolicy }}
          securityContext:
            privileged: false
            runAsUser: 1001
          args: ["gotenberg", "--api-port=3030"]
          ports:
            - name: http
              containerPort: 3030
              protocol: TCP
      volumes:
        - name: data-volume
          emptyDir:
      affinity:
        {{- toYaml .Values.cdn.affinity | nindent 8 }}
      tolerations:
        {{- toYaml .Values.cdn.tolerations | nindent 8 }}
