apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: "{{ include "bookyp.fullname" . }}-payment"
  labels:
    {{- include "bookyp.labels" . | nindent 4 }}
  {{- with .Values.payment.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`{{ include "bookyp.paymentURL" . }}`)
      kind: Rule
      services:
        - name: "{{ include "bookyp.fullname" . }}-payment"
          port: 3000
  tls:
    secretName: {{ .Values.payment.ingress.tls.secretName }}
