apiVersion: v1
kind: Secret
metadata:
  name: "{{ include "bookyp.fullname" . }}-payment-secret"
  labels:
    {{- include "bookyp.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_URL: {{ include "bookyp.paymentDatabaseURI" . | quote }}
  ADMIN_TOKEN: {{ .Values.payment.adminToken }}
  CREATE_PROJECT_DATA: |
    {
      "name": "Bookyp",
      "mollieApiKey": "{{ .Values.payment.mollieToken }}",
      "apiToken": "{{ .Values.payment.projectToken }}",
      "paymentProvider": "mollie",
      "webhookUrl": "https://{{ include "bookyp.backendURL" . }}/payments/webhook",
      "invoiceData": {
        "email": "info@geprog.com",
        "name": "Geprog GmbH",
        "addressLine1": "Schauenburgerstr. 116",
        "addressLine2": "",
        "zipCode": "24118",
        "city": "Kiel",
        "country": "Germany",
        "logo": "https://geprog.com/logo.svg"
      }
    }
