environment:
  type: production
  name: production

imagePullSecrets:
  - name: bookyp-registry-secret

frontend:
  ingress:
    tls:
      secretName: bookyp-production-tls

backend:
  ingress:
    tls:
      secretName: bookyp-production-tls
