apiVersion: v1
kind: Secret
metadata:
  name: "{{ include "bookyp.fullname" . }}-cdn-secret"
  labels:
    {{- include "bookyp.labels" . | nindent 4 }}
type: Opaque
stringData:
  S3WWW_SECRET_KEY: {{ .Values.cdn.s3.secretKey | quote }}
