# This file is used for local development (devcontainer)

version: '3.8'

services:
  db:
    image: mongo:4.4-bionic
    volumes:
      - mongodb-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME:-root}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD:-supersecret}

  mongo-express:
    image: mongo-express
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${DB_USERNAME:-root}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${DB_PASSWORD:-supersecret}
      ME_CONFIG_MONGODB_SERVER: localhost
    network_mode: service:db
    restart: unless-stopped
    depends_on:
      - db

  mail:
    image: mailhog/mailhog
    ports:
      - '127.0.0.1:1025:1025'
      - '127.0.0.1:8025:8025'

  s3:
    image: minio/minio
    volumes:
      - minio-data:/data
    environment:
      MINIO_ROOT_USER: ${S3_ACCESS_KEY:-root}
      MINIO_ROOT_PASSWORD: ${S3_SECRET_KEY:-supersecret}
    command: server /data --console-address ":9001"

  s3www:
    image: anbraten/s3www:v0.6.8
    environment:
      S3WWW_ADDRESS: '0.0.0.0:8080'
      S3WWW_ENDPOINT: http://s3:9000
      S3WWW_ACCESS_KEY: ${S3_ACCESS_KEY:-root}
      S3WWW_SECRET_KEY: ${S3_SECRET_KEY:-supersecret}
      S3WWW_BUCKET: ${S3_BUCKET:-bookyp-files}

volumes:
  mongodb-data:
  minio-data:
