# This file is used for local development (devcontainer)

version: '3.8'

services:
  db:
    image: mongo:4.4-bionic
    volumes:
      - mongodb-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME:-root}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD:-supersecret}

  mongo-express:
    image: mongo-express
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${DB_USERNAME:-root}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${DB_PASSWORD:-supersecret}
      ME_CONFIG_MONGODB_SERVER: localhost
    network_mode: service:db
    depends_on:
      - db

volumes:
  mongodb-data:
