# This file is used for local development (devcontainer)

version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 9300:3000
      - 9301:4000
    volumes:
      - ..:/workspace:cached
      # add local ssh config
      - ~/.ssh:/.ssh-localhost:ro
