# This file is used for local development (devcontainer)

version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - 3000:3000
      - 4000:4000
    volumes:
      - ..:/workspace:cached
      # add local ssh config
      - ~/.ssh:/.ssh-localhost:ro
