---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: bookyp-production-certificate
spec:
  secretName: bookyp-production-tls
  commonName: app.bookyp.de
  dnsNames:
    - app.bookyp.de
    - api.bookyp.de
    - cdn.bookyp.de
    - payment.bookyp.de
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
