---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: bookyp-review-frontend-certificate
spec:
  secretName: bookyp-review-frontend-tls
  commonName: '*.app.bookyp.de'
  dnsNames:
    - app.bookyp.de
    - '*.app.bookyp.de'
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: bookyp-review-backend-certificate
spec:
  secretName: bookyp-review-backend-tls
  commonName: '*.api.bookyp.de'
  dnsNames:
    - api.bookyp.de
    - '*.api.bookyp.de'
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: bookyp-review-cdn-certificate
spec:
  secretName: bookyp-review-cdn-tls
  commonName: '*.cdn.bookyp.de'
  dnsNames:
    - cdn.bookyp.de
    - '*.cdn.bookyp.de'
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
