---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: bookyp-review-frontend-certificate
spec:
  secretName: bookyp-review-frontend-tls
  commonName: '*.app.bookyp.de'
  dnsNames:
    - app.bookyp.de
    - '*.app.bookyp.de'
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer

---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: bookyp-review-backend-certificate
spec:
  secretName: bookyp-review-backend-tls
  commonName: '*.api.bookyp.de'
  dnsNames:
    - api.bookyp.de
    - '*.api.bookyp.de'
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer

---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: bookyp-storybook-review-certificate
spec:
  secretName: bookyp-storybook-review-tls
  commonName: '*.storybook.bookyp.de'
  dnsNames:
    - storybook.bookyp.de
    - '*.storybook.bookyp.de'
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
